version: '3.8'

services:
  backend:
    build: ./backend
    container_name: tree_backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
    restart: always

  frontend:
    build: ./frontend
    container_name: tree_frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    restart: always